
/*Table Creation*/
CREATE TABLE `freight_management`.`place` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `CODE` varchar(45) NOT NULL,
  `ADDRESS` varchar(255) DEFAULT NULL,
  `LONGITUDE` double NOT NULL,
  `LATITUDE` double NOT NULL,
  `CREATED_BY` varchar(45) NOT NULL DEFAULT 'ADMIN',
  `UPDATED_BY` varchar(45) DEFAULT NULL,
  `CREATED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CODE_UNIQUE` (`CODE`),
  UNIQUE KEY `NAME_UNIQUE` (`NAME`)
) ;

CREATE TABLE `freight_management`.`path` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FROM_CODE` varchar(45) NOT NULL,
  `TO_CODE` varchar(45) NOT NULL,
  `CONTAINER_SIZE_FEET` int(11) NOT NULL,
  `COST_EURO` double NOT NULL,
  `ROUTE_TYPE` varchar(45) NOT NULL,
  `DURATION_DAY` int(11) NOT NULL,
  `CREATED_BY` varchar(255) NOT NULL DEFAULT 'ADMIN',
  `UPDATED_BY` varchar(255) DEFAULT NULL,
  `CREATED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `unique_container_route` (`FROM_CODE`,`TO_CODE`,`CONTAINER_SIZE_FEET`,`ROUTE_TYPE`),
  KEY `FK_FROM_idx` (`FROM_CODE`),
  KEY `FK_TO_idx` (`TO_CODE`),
  CONSTRAINT `FK_FROM` FOREIGN KEY (`FROM_CODE`) REFERENCES `place` (`CODE`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_TO` FOREIGN KEY (`TO_CODE`) REFERENCES `place` (`CODE`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ;